# Generated by Django 2.2.6 on 2021-06-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20210614_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=90)),
                ('last_name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(default='', max_length=111)),
                ('picture', models.ImageField(default='', upload_to='DriverApp/images')),
                ('promo_code', models.CharField(max_length=111)),
                ('activation_status', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
