# Generated by Django 2.2.6 on 2021-06-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_driver_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='driver',
            name='password',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='driver',
            name='promo_code',
            field=models.CharField(max_length=10),
        ),
    ]
