# Generated by Django 2.2.6 on 2021-06-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_driver_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='activation_status',
        ),
    ]
