# Generated by Django 2.2.6 on 2021-06-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_remove_driver_activation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='username',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
