# Generated by Django 2.2.6 on 2021-06-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_driver_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
