# Generated by Django 3.1.7 on 2021-05-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='picture',
            field=models.ImageField(default='', upload_to='Driver/images'),
        ),
    ]
