# Generated by Django 3.1.7 on 2021-05-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverApp', '0002_auto_20210511_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='picture',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
