# Generated by Django 3.1.7 on 2021-05-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverApp', '0003_auto_20210511_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.CharField(choices=[('excellent', 1), ('average', 0), ('bad', -1)], default='average', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='picture',
            field=models.ImageField(default='', upload_to='Driver/images'),
        ),
    ]
