# Generated by Django 3.1.7 on 2021-05-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverApp', '0004_auto_20210511_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
