# Generated by Django 3.1.7 on 2021-05-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverApp', '0005_auto_20210511_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='picture',
            field=models.ImageField(default='', upload_to='DriverApp/images'),
        ),
    ]
