# Generated by Django 2.2.6 on 2021-06-21 09:11

from django.db import migrations, models
import location_field.models.plain
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('driver_fname', models.CharField(max_length=90)),
                ('driver_lname', models.CharField(max_length=90)),
                ('driver_address', models.CharField(max_length=90)),
                ('driver_city', models.CharField(max_length=90)),
                ('driver_phone', models.CharField(max_length=15)),
                ('driver_email', models.EmailField(max_length=255)),
                ('driver_location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('driver_photo', models.ImageField(default='', upload_to='DeliveryApp/images')),
                ('is_status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='driver_vehical',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('vehical_type_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('vehical_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('home_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('home_name', models.CharField(max_length=90)),
                ('home_address', models.CharField(max_length=90)),
                ('home_city', models.CharField(max_length=90)),
                ('home_phone', models.CharField(max_length=15)),
                ('home_email', models.EmailField(max_length=255)),
                ('home_location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('home_logo', models.ImageField(default='', upload_to='DeliveryApp/images')),
                ('is_status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='job_driver_map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='job_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='job_mst',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='job_packet_map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('packet_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='order_mst',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='order_packet_map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('packet_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='packet_mst',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('packet_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('packet_qrcode', models.TextField()),
                ('home_location', models.FloatField(max_length=100, unique=True)),
                ('delivery_location', models.FloatField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('patient_fname', models.CharField(max_length=90)),
                ('patient_lname', models.CharField(max_length=90)),
                ('patient_phone', models.CharField(max_length=15)),
                ('patient_email', models.EmailField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='role_mst',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_code', models.CharField(max_length=90)),
                ('rol_name', models.CharField(max_length=90)),
                ('is_active', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('store_name', models.CharField(max_length=90)),
                ('store_address', models.CharField(max_length=90)),
                ('store_phone', models.CharField(max_length=15)),
                ('store_email', models.EmailField(max_length=255)),
                ('store_city', models.CharField(max_length=111)),
                ('store_location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('store_logo', models.ImageField(default='', upload_to='DeliveryApp/images')),
                ('is_status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='user_driver_map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('driver_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_home_map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('home_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_patient_map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('patient_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_pharmacy_map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('store_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='vehical_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehical_type_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('vehical_type', models.CharField(max_length=90)),
                ('vehical_type_desc', models.CharField(max_length=500)),
                ('vehical_type_img', models.ImageField(default='', upload_to='DeliveryApp/Vehical_type/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
