# Generated by Django 2.2.6 on 2021-06-21 09:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_mst',
            fields=[
                ('user_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('username', models.CharField(max_length=90)),
                ('password', models.CharField(default='', max_length=65)),
                ('role_code', models.CharField(max_length=90)),
                ('promo_code', models.CharField(max_length=111)),
                ('ref_promo_code', models.CharField(max_length=111)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DeliveryApp.User')),
            ],
        ),
    ]
