# Generated by Django 2.2.6 on 2021-06-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0002_user_mst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_mst',
            name='user',
        ),
        migrations.AddField(
            model_name='user_mst',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
