# Generated by Django 2.2.6 on 2021-06-21 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0007_auto_20210621_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_mst',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_mst',
            name='role_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DeliveryApp.role_mst'),
        ),
    ]
