# Generated by Django 3.1.7 on 2021-05-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0004_auto_20210513_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='name',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='website',
            field=models.TextField(default=-1.0, max_length=100),
            preserve_default=False,
        ),
    ]
