# Generated by Django 3.1.7 on 2021-05-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0005_auto_20210514_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='website',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
