# Generated by Django 3.1.7 on 2021-05-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0007_qrcode_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
