# Generated by Django 3.1.7 on 2021-05-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0008_auto_20210514_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='name',
        ),
    ]
